import AppKit
import Foundation

/// Polls the pasteboard's change counter and records new text clips.
/// Reading `changeCount` is cheap, so the real pasteboard contents are only
/// touched when something actually changed.
final class Watcher {
    private let store: Store
    private let config: Config
    private var lastChangeCount: Int

    /// Markers that well-behaved apps (password managers, clipboard tools)
    /// set to say "do not record this".
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
    ]

    init(store: Store, config: Config) {
        self.store = store
        self.config = config
        self.lastChangeCount = pasteboard.changeCount
    }

    func run() -> Never {
        // Captured strongly on purpose: `run()` never returns, so the watcher
        // must outlive this scope for the timer to keep firing.
        let timer = Timer(timeInterval: config.pollSeconds, repeats: true) { _ in
            self.tick()
        }
        RunLoop.main.add(timer, forMode: .common)
        FileHandle.standardError.write("clipstack: watching pasteboard (every \(config.pollSeconds)s)\n".data(using: .utf8)!)
        RunLoop.main.run()
        fatalError("run loop exited")
    }

    private func tick() {
        let pb = pasteboard
        let count = pb.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        guard let types = pb.types else { return }
        if types.contains(where: { Watcher.privateTypes.contains($0.rawValue) }) { return }

        let front = NSWorkspace.shared.frontmostApplication
        if let bundleID = front?.bundleIdentifier, config.ignoredBundleIDs.contains(bundleID) { return }

        // File copies arrive as URLs; record their paths so they are still greppable.
        if types.contains(.fileURL),
           let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map(\.path).joined(separator: "\n")
            store.add(text: paths, app: front?.localizedName)
            return
        }

        guard let text = pb.string(forType: .string) else { return }
        store.add(text: text, app: front?.localizedName)
    }
}
